from flask import Blueprint
from flask_restx import Api
from .resources import namespaces

bp_api = Blueprint("api", "__name__", url_prefix="/api")

authorizations = {
    'jwt' : {
        'type' : 'apiKey',
        'in' : 'header',
        'name' : 'Authorization',
        'description': 'Bearer token generated by /auth endpoint.'
    }
}

api = Api(bp_api, title='Base blueprint for a new API RESTful', doc='/swagger', authorizations=authorizations)

for ns in namespaces:
    api.add_namespace(ns)
    